from panormus.config.settings import ALIB_HOL_FILE_DIR

HOLIDAY_PATH = ALIB_HOL_FILE_DIR

SWAPITON_CONV_DICT = {
    'USD.3ML': {
        'barc_settlement_type': 'phys',
    },
    'EUR.6ML': {
        'barc_settlement_type': 'cash',
    },
    'GBP.6ML': {
        'barc_settlement_type': 'cash',
    },
}

CONV_DICT = {
    'USD.OIS': {
        'fixed_interval': '1Y',
        'fixed_dcc': 'act/360',
        'float_interval': '1Y',
        'float_rate_interval': '1D',
        'float_dcc': 'act/360',
        'stub_method': 'f/s',
        'convexity_adjust': 0,
        'vol_model': 'NULL',
        'accrual_bad_day_conv': 'M',
        'pay_bad_day_conv': 'M',
        'reset_bad_day_conv': 'N',
        'principal_final_flag': 0,
        'principal_initial_flag': 0,
        'holiday_calendar_name': 'GBP+USD.FX',
        'fixing_offset': -2
    },
    'USD.1ML': {
        'fixed_interval': '1Y',
        'fixed_dcc': '30/360',
        'float_interval': '1M',
        'float_rate_interval': '1M',
        'float_dcc': 'act/360',
        'stub_method': 'f/s',
        'convexity_adjust': 0,
        'vol_model': 'NULL',
        'accrual_bad_day_conv': 'M',
        'pay_bad_day_conv': 'M',
        'reset_bad_day_conv': 'M',
        'principal_final_flag': 0,
        'principal_initial_flag': 0,
        'holiday_calendar_name': 'GBP+USD.FX',
        'fixing_offset': -2,
    },
    'USD.3ML': {
        'fixed_interval': '6M',
        'fixed_dcc': '30/360',
        'float_interval': '3M',
        'float_rate_interval': '3M',
        'float_dcc': 'act/360',
        'stub_method': 'f/s',
        'convexity_adjust': 0,
        'vol_model': 'NULL',
        'accrual_bad_day_conv': 'M',
        'pay_bad_day_conv': 'M',
       'reset_bad_day_conv': 'M',
        'principal_final_flag': 0,
        'principal_initial_flag': 0,
        'holiday_calendar_name': 'GBP+USD.FX',
        'fixing_offset': -2
    },
    'USD.6ML': {
        'fixed_interval': '6M',
        'fixed_dcc': '30/360',
        'float_interval': '6M',
        'float_rate_interval': '6M',
        'float_dcc': 'act/360',
        'stub_method': 'f/s',
        'convexity_adjust': 0,
        'vol_model': 'NULL',
        'accrual_bad_day_conv': 'M',
        'pay_bad_day_conv': 'M',
        'reset_bad_day_conv': 'M',
        'principal_final_flag': 0,
        'principal_initial_flag': 0,
        'holiday_calendar_name': 'GBP+USD.FX',
        'fixing_offset': -2
    },
    'USD.3ML.IMM': {
        'fixed_interval': '2i',
        'fixed_dcc': '30/360',
        'float_interval': '1i',
        'float_rate_interval': '3M',
        'float_dcc': 'act/360',
        'stub_method': 'f/s',
        'convexity_adjust': 0,
        'vol_model': 'NULL',
        'accrual_bad_day_conv': 'M',
        'pay_bad_day_conv': 'M',
        'reset_bad_day_conv': 'M',
        'principal_final_flag': 0,
        'principal_initial_flag': 0,
        'holiday_calendar_name': 'GBP+USD.FX',
        'fixing_offset': -2
    },
    'CHF.OIS': {
        'fixed_interval': '1Y',
        'fixed_dcc': 'act/360',
        'float_interval': '1Y',
        'float_rate_interval': '1D',
        'float_dcc': 'act/360',
        'stub_method': 'f/s',
        'convexity_adjust': 0,
        'vol_model': 'NULL',
        'accrual_bad_day_conv': 'M',
        'pay_bad_day_conv': 'M',
        'reset_bad_day_conv': 'N',
        'principal_final_flag': 0,
        'principal_initial_flag': 0,
        'holiday_calendar_name': 'GBP+CHF',
        'fixing_offset': -2
    },
    'CHF.1ML': {
        'fixed_interval': '1Y',
        'fixed_dcc': '30/360',
        'float_interval': '1M',
        'float_rate_interval': '1M',
        'float_dcc': 'act/360',
        'stub_method': 'f/s',
        'convexity_adjust': 0,
        'vol_model': 'NULL',
        'accrual_bad_day_conv': 'M',
        'pay_bad_day_conv': 'M',
        'reset_bad_day_conv': 'M',
        'principal_final_flag': 0,
        'principal_initial_flag': 0,
        'holiday_calendar_name': 'GBP+CHF',
        'fixing_offset': -2
    },
    'CHF.3ML': {
        'fixed_interval': '1Y',
        'fixed_dcc': '30/360',
        'float_interval': '3M',
        'float_rate_interval': '3M',
        'float_dcc': 'act/360',
        'stub_method': 'f/s',
        'convexity_adjust': 0,
        'vol_model': 'NULL',
        'accrual_bad_day_conv': 'M',
        'pay_bad_day_conv': 'M',
        'reset_bad_day_conv': 'M',
        'principal_final_flag': 0,
        'principal_initial_flag': 0,
        'holiday_calendar_name': 'GBP+CHF',
        'fixing_offset': -2
    },
    'CHF.6ML': {
        'fixed_interval': '1Y',
        'fixed_dcc': '30/360',
        'float_interval': '6M',
        'float_rate_interval': '6M',
        'float_dcc': 'act/360',
        'stub_method': 'f/s',
        'convexity_adjust': 0,
        'vol_model': 'NULL',
        'accrual_bad_day_conv': 'M',
        'pay_bad_day_conv': 'M',
        'reset_bad_day_conv': 'M',
        'principal_final_flag': 0,
        'principal_initial_flag': 0,
        'holiday_calendar_name': 'GBP+CHF',
        'fixing_offset': -2
    },
    'EUR.OIS': {
        'fixed_interval': '1Y',
        'fixed_dcc': 'act/360',
        'float_interval': '1Y',
        'float_rate_interval': '1D',
        'float_dcc': 'act/360',
        'stub_method': 'f/s',
        'convexity_adjust': 0,
        'vol_model': 'NULL',
        'accrual_bad_day_conv': 'M',
        'pay_bad_day_conv': 'M',
        'reset_bad_day_conv': 'N',
        'principal_final_flag': 0,
        'principal_initial_flag': 0,
        'holiday_calendar_name': 'EUR',
        'fixing_offset': -2
    },
    'EUR.1ML': {
        'fixed_interval': '1Y',
        'fixed_dcc': '30E/360',
        'float_interval': '1M',
        'float_rate_interval': '1M',
        'float_dcc': 'act/360',
        'stub_method': 'f/s',
        'convexity_adjust': 0,
        'vol_model': 'NULL',
        'accrual_bad_day_conv': 'M',
        'pay_bad_day_conv': 'M',
        'reset_bad_day_conv': 'M',
        'principal_final_flag': 0,
        'principal_initial_flag': 0,
        'holiday_calendar_name': 'EUR',
        'fixing_offset': -2
    },
    'EUR.3ML': {
        'fixed_interval': '1Y',
        'fixed_dcc': '30E/360',
        'float_interval': '3M',
        'float_rate_interval': '3M',
        'float_dcc': 'act/360',
        'stub_method': 'f/s',
        'convexity_adjust': 0,
        'vol_model': 'NULL',
        'accrual_bad_day_conv': 'M',
        'pay_bad_day_conv': 'M',
        'reset_bad_day_conv': 'M',
        'principal_final_flag': 0,
        'principal_initial_flag': 0,
        'holiday_calendar_name': 'EUR',
        'fixing_offset': -2
    },
    'EUR.6ML': {
        'fixed_interval': '1Y',
        'fixed_dcc': '30E/360',
        'float_interval': '6M',
        'float_rate_interval': '6M',
        'float_dcc': 'act/360',
        'stub_method': 'f/s',
        'convexity_adjust': 0,
        'vol_model': 'NULL',
        'accrual_bad_day_conv': 'M',
        'pay_bad_day_conv': 'M',
        'reset_bad_day_conv': 'M',
        'principal_final_flag': 0,
        'principal_initial_flag': 0,
        'holiday_calendar_name': 'EUR',
        'fixing_offset': -2
    },
    'EUR.3ML.IMM': {
        'fixed_interval': '4i',
        'fixed_dcc': '30E/360',
        'float_interval': '1i',
        'float_rate_interval': '3M',
        'float_dcc': 'act/360',
        'stub_method': 'f/s',
        'convexity_adjust': 0,
        'vol_model': 'NULL',
        'accrual_bad_day_conv': 'M',
        'pay_bad_day_conv': 'M',
        'reset_bad_day_conv': 'M',
        'principal_final_flag': 0,
        'principal_initial_flag': 0,
        'holiday_calendar_name': 'EUR',
        'fixing_offset': -2
    },
    'EUR.6ML.IMM': {
        'fixed_interval': '4i',
        'fixed_dcc': '30E/360',
        'float_interval': '2i',
        'float_rate_interval': '6M',
        'float_dcc': 'act/360',
        'stub_method': 'f/s',
        'convexity_adjust': 0,
        'vol_model': 'NULL',
        'accrual_bad_day_conv': 'M',
        'pay_bad_day_conv': 'M',
        'reset_bad_day_conv': 'M',
        'principal_final_flag': 0,
        'principal_initial_flag': 0,
        'holiday_calendar_name': 'EUR',
        'fixing_offset': -2
    },
    'GBP.OIS': {
        'fixed_interval': '1Y',
        'fixed_dcc': 'act/365F',
        'float_interval': '1Y',
        'float_rate_interval': '1D',
        'float_dcc': 'act/365F',
        'stub_method': 'f/s',
        'convexity_adjust': 0,
        'vol_model': 'NULL',
        'accrual_bad_day_conv': 'M',
        'pay_bad_day_conv': 'M',
        'reset_bad_day_conv': 'N',
        'principal_final_flag': 0,
        'principal_initial_flag': 0,
        'holiday_calendar_name': 'GBP',
        'fixing_offset': 0
    },
    'GBP.1ML': {
        'fixed_interval': '1Y',
        'fixed_dcc': 'act/365F',
       'float_interval': '1M',
        'float_rate_interval': '1M',
        'float_dcc': 'act/365F',
        'stub_method': 'f/s',
        'convexity_adjust': 0,
        'vol_model': 'NULL',
        'accrual_bad_day_conv': 'M',
        'pay_bad_day_conv': 'M',
        'reset_bad_day_conv': 'M',
        'principal_final_flag': 0,
        'principal_initial_flag': 0,
        'holiday_calendar_name': 'GBP',
        'fixing_offset': 0
    },
    'GBP.3ML': {
        'fixed_interval': '3M',
        'fixed_dcc': 'act/365F',
        'float_interval': '3M',
        'float_rate_interval': '3M',
        'float_dcc': 'act/365F',
        'stub_method': 'f/s',
        'convexity_adjust': 0,
        'vol_model': 'NULL',
        'accrual_bad_day_conv': 'M',
        'pay_bad_day_conv': 'M',
        'reset_bad_day_conv': 'M',
        'principal_final_flag': 0,
        'principal_initial_flag': 0,
        'holiday_calendar_name': 'GBP',
        'fixing_offset': 0
    },
    'GBP.6ML': {
        'fixed_interval': '6M',
        'fixed_dcc': 'act/365F',
        'float_interval': '6M',
        'float_rate_interval': '6M',
        'float_dcc': 'act/365F',
        'stub_method': 'f/s',
        'convexity_adjust': 0,
        'vol_model': 'NULL',
        'accrual_bad_day_conv': 'M',
        'pay_bad_day_conv': 'M',
        'reset_bad_day_conv': 'M',
        'principal_final_flag': 0,
        'principal_initial_flag': 0,
        'holiday_calendar_name': 'GBP',
        'fixing_offset': 0
    },
    'GBP.3ML.IMM': {
        'fixed_interval': '4i',
        'fixed_dcc': 'act/365F',
        'float_interval': '1i',
        'float_rate_interval': '3M',
        'float_dcc': 'act/365F',
        'stub_method': 'f/s',
        'convexity_adjust': 0,
        'vol_model': 'NULL',
        'accrual_bad_day_conv': 'M',
        'pay_bad_day_conv': 'M',
        'reset_bad_day_conv': 'M',
        'principal_final_flag': 0,
        'principal_initial_flag': 0,
        'holiday_calendar_name': 'GBP',
        'fixing_offset': 0
    },
    'GBP.6ML.IMM': {
        'fixed_interval': '2i',
        'fixed_dcc': 'act/365F',
        'float_interval': '2i',
        'float_rate_interval': '6M',
        'float_dcc': 'act/365F',
        'stub_method': 'f/s',
        'convexity_adjust': 0,
        'vol_model': 'NULL',
        'accrual_bad_day_conv': 'M',
        'pay_bad_day_conv': 'M',
        'reset_bad_day_conv': 'M',
        'principal_final_flag': 0,
        'principal_initial_flag': 0,
        'holiday_calendar_name': 'GBP',
        'fixing_offset': 0
    },
    'CAD.OIS': {
        'fixed_interval': '1Y',
        'fixed_dcc': 'act/365F',
        'float_interval': '1Y',
        'float_rate_interval': '1D',
        'float_dcc': 'act/365F',
        'stub_method': 'f/s',
        'convexity_adjust': 0,
        'vol_model': 'NULL',
        'accrual_bad_day_conv': 'M',
        'pay_bad_day_conv': 'M',
        'reset_bad_day_conv': 'N',
        'principal_final_flag': 0,
        'principal_initial_flag': 0,
        'holiday_calendar_name': 'CAD',
        'fixing_offset': 0
    },
    'CAD.3ML': {
        'fixed_interval': '6M',
        'fixed_dcc': 'act/365F',
        'float_interval': '6M',
        'float_rate_interval': '3M',
        'float_dcc': 'act/365F',
        'stub_method': 'f/s',
        'convexity_adjust': 0,
        'vol_model': 'NULL',
        'accrual_bad_day_conv': 'M',
        'pay_bad_day_conv': 'M',
        'reset_bad_day_conv': 'M',
        'principal_final_flag': 0,
        'principal_initial_flag': 0,
        'holiday_calendar_name': 'CAD',
        'fixing_offset': 0
    },
    'CAD.3ML.SD': {
        'fixed_interval': '6M',
        'fixed_dcc': 'act/365F',
        'float_interval': '6M',
        'float_rate_interval': '3M',
        'float_dcc': 'act/365F',
        'stub_method': 'f/s',
        'convexity_adjust': 0,
        'vol_model': 'NULL',
        'accrual_bad_day_conv': 'M',
        'pay_bad_day_conv': 'M',
        'reset_bad_day_conv': 'M',
        'principal_final_flag': 0,
        'principal_initial_flag': 0,
        'holiday_calendar_name': 'CAD',
        'fixing_offset': 0
    },
    'JPY.OIS': {
        'fixed_interval': '1Y',
        'fixed_dcc': 'act/365F',
        'float_interval': '1Y',
        'float_rate_interval': '1D',
        'float_dcc': 'act/365F',
        'stub_method': 'f/s',
        'convexity_adjust': 0,
        'vol_model': 'NULL',
        'accrual_bad_day_conv': 'M',
        'pay_bad_day_conv': 'M',
        'reset_bad_day_conv': 'N',
        'principal_final_flag': 0,
        'principal_initial_flag': 0,
        'holiday_calendar_name': 'JPY',
        'fixing_offset': -2
    },
    'JPY.1ML': {
        'fixed_interval': '1Y',
        'fixed_dcc': 'act/360',
        'float_interval': '1M',
        'float_rate_interval': '1M',
        'float_dcc': 'act/360',
        'stub_method': 'f/s',
        'convexity_adjust': 0,
        'vol_model': 'NULL',
        'accrual_bad_day_conv': 'M',
        'pay_bad_day_conv': 'M',
        'reset_bad_day_conv': 'M',
        'principal_final_flag': 0,
        'principal_initial_flag': 0,
        'holiday_calendar_name': 'GBP+JPY',
        'fixing_offset': -2
    },
    'JPY.3ML': {
        'fixed_interval': '1Y',
        'fixed_dcc': 'act/360',
        'float_interval': '3M',
        'float_rate_interval': '3M',
        'float_dcc': 'act/360',
        'stub_method': 'f/s',
        'convexity_adjust': 0,
        'vol_model': 'NULL',
        'accrual_bad_day_conv': 'M',
        'pay_bad_day_conv': 'M',
        'reset_bad_day_conv': 'M',
        'principal_final_flag': 0,
        'principal_initial_flag': 0,
        'holiday_calendar_name': 'GBP+JPY',
        'fixing_offset': -2
    },
    'JPY.6ML': {
        'fixed_interval': '6M',
        'fixed_dcc': 'act/365F',
        'float_interval': '6M',
        'float_rate_interval': '6M',
        'float_dcc': 'act/360',
        'stub_method': 'f/s',
        'convexity_adjust': 0,
        'vol_model': 'NULL',
        'accrual_bad_day_conv': 'M',
        'pay_bad_day_conv': 'M',
        'reset_bad_day_conv': 'M',
        'principal_final_flag': 0,
        'principal_initial_flag': 0,
        'holiday_calendar_name': 'GBP+JPY',
        'fixing_offset': -2
    },
    'JPY.6ML.SD': {
        'fixed_interval': '6M',
        'fixed_dcc': 'act/365F',
        'float_interval': '6M',
        'float_rate_interval': '6M',
        'float_dcc': 'act/360',
        'stub_method': 'f/s',
        'convexity_adjust': 0,
        'vol_model': 'NULL',
        'accrual_bad_day_conv': 'M',
        'pay_bad_day_conv': 'M',
        'reset_bad_day_conv': 'M',
        'principal_final_flag': 0,
        'principal_initial_flag': 0,
        'holiday_calendar_name': 'GBP+JPY',
        'fixing_offset': -2
    },
    'SEK.OIS': {
        'fixed_interval': '1Y',
        'fixed_dcc': 'act/360',
        'float_interval': '1Y',
        'float_rate_interval': '1D',
        'float_dcc': 'act/360',
        'stub_method': 'f/s',
        'convexity_adjust': 0,
        'vol_model': 'NULL',
        'accrual_bad_day_conv': 'M',
        'pay_bad_day_conv': 'M',
        'reset_bad_day_conv': 'N',
        'principal_final_flag': 0,
        'principal_initial_flag': 0,
        'holiday_calendar_name': 'SEK',
        'fixing_offset': -2
    },
    'SEK.3ML': {
        'fixed_interval': '1Y',
        'fixed_dcc': '30/360',
        'float_interval': '3M',
        'float_rate_interval': '3M',
        'float_dcc': 'act/360',
        'stub_method': 'f/s',
        'convexity_adjust': 0,
        'vol_model': 'NULL',
        'accrual_bad_day_conv': 'M',
        'pay_bad_day_conv': 'M',
        'reset_bad_day_conv': 'M',
        'principal_final_flag': 0,
        'principal_initial_flag': 0,
        'holiday_calendar_name': 'SEK',
        'fixing_offset': -2
    },
    'AUD.OIS': {
        'fixed_interval': '1Y',
        'fixed_dcc': 'act/365F',
        'float_interval': '1Y',
        'float_rate_interval': '1D',
        'float_dcc': 'act/365F',
        'stub_method': 'f/s',
        'convexity_adjust': 0,
        'vol_model': 'NULL',
        'accrual_bad_day_conv': 'M',
        'pay_bad_day_conv': 'M',
        'reset_bad_day_conv': 'N',
        'principal_final_flag': 0,
        'principal_initial_flag': 0,
        'holiday_calendar_name': 'AUD',
        'fixing_offset': -1
    },
    'AUD.3ML': {
        'fixed_interval': '3M',
        'fixed_dcc': 'act/365F',
        'float_interval': '3M',
        'float_rate_interval': '3M',
        'float_dcc': 'act/365F',
        'stub_method': 'f/s',
        'convexity_adjust': 0,
        'vol_model': 'NULL',
        'accrual_bad_day_conv': 'M',
        'pay_bad_day_conv': 'M',
        'reset_bad_day_conv': 'M',
        'principal_final_flag': 0,
        'principal_initial_flag': 0,
        'holiday_calendar_name': 'AUD',
        'fixing_offset': -1
    },
    'AUD.6ML': {
        'fixed_interval': '6M',
        'fixed_dcc': 'act/365F',
        'float_interval': '6M',
        'float_rate_interval': '6M',
        'float_dcc': 'act/365F',
        'stub_method': 'f/s',
        'convexity_adjust': 0,
        'vol_model': 'NULL',
        'accrual_bad_day_conv': 'M',
        'pay_bad_day_conv': 'M',
        'reset_bad_day_conv': 'M',
        'principal_final_flag': 0,
        'principal_initial_flag': 0,
        'holiday_calendar_name': 'AUD',
        'fixing_offset': -1
    },
    'NOK.OIS': {
        'fixed_interval': '1Y',
        'fixed_dcc': 'act/360',
        'float_interval': '1Y',
        'float_rate_interval': '1D',
        'float_dcc': 'act/360',
        'stub_method': 'f/s',
        'convexity_adjust': 0,
        'vol_model': 'NULL',
        'accrual_bad_day_conv': 'M',
        'pay_bad_day_conv': 'M',
        'reset_bad_day_conv': 'N',
        'principal_final_flag': 0,
        'principal_initial_flag': 0,
        'holiday_calendar_name': 'NOK',
        'fixing_offset': -2
    },
    'NOK.3ML': {
        'fixed_interval': '1Y',
        'fixed_dcc': '30/360',
        'float_interval': '3M',
        'float_rate_interval': '3M',
        'float_dcc': 'act/360',
        'stub_method': 'f/s',
        'convexity_adjust': 0,
        'vol_model': 'NULL',
        'accrual_bad_day_conv': 'M',
        'pay_bad_day_conv': 'M',
        'reset_bad_day_conv': 'M',
        'principal_final_flag': 0,
        'principal_initial_flag': 0,
        'holiday_calendar_name': 'NOK',
        'fixing_offset': -2
    },
    'NOK.6ML': {
        'fixed_interval': '1Y',
        'fixed_dcc': '30/360',
        'float_interval': '6M',
        'float_rate_interval': '6M',
        'float_dcc': 'act/360',
        'stub_method': 'f/s',
        'convexity_adjust': 0,
        'vol_model': 'NULL',
        'accrual_bad_day_conv': 'M',
        'pay_bad_day_conv': 'M',
        'reset_bad_day_conv': 'M',
        'principal_final_flag': 0,
        'principal_initial_flag': 0,
        'holiday_calendar_name': 'NOK',
        'fixing_offset': -2
    },
    'DKK.OIS': {
        'fixed_interval': '1Y',
        'fixed_dcc': 'act/360',
        'float_interval': '1Y',
        'float_rate_interval': '1D',
        'float_dcc': 'act/360',
        'stub_method': 'f/s',
        'convexity_adjust': 0,
        'vol_model': 'NULL',
        'accrual_bad_day_conv': 'M',
        'pay_bad_day_conv': 'M',
        'reset_bad_day_conv': 'N',
        'principal_final_flag': 0,
        'principal_initial_flag': 0,
        'holiday_calendar_name': 'DKK',
        'fixing_offset': -2
    },
    'DKK.3ML': {
        'fixed_interval': '1Y',
        'fixed_dcc': '30/360',
        'float_interval': '3M',
        'float_rate_interval': '3M',
        'float_dcc': 'act/360',
        'stub_method': 'f/s',
        'convexity_adjust': 0,
        'vol_model': 'NULL',
        'accrual_bad_day_conv': 'M',
        'pay_bad_day_conv': 'M',
        'reset_bad_day_conv': 'M',
        'principal_final_flag': 0,
        'principal_initial_flag': 0,
        'holiday_calendar_name': 'DKK',
        'fixing_offset': -2
    },
    'DKK.6ML': {
        'fixed_interval': '1Y',
        'fixed_dcc': '30/360',
        'float_interval': '6M',
        'float_rate_interval': '6M',
        'float_dcc': 'act/360',
        'stub_method': 'f/s',
        'convexity_adjust': 0,
        'vol_model': 'NULL',
        'accrual_bad_day_conv': 'M',
        'pay_bad_day_conv': 'M',
        'reset_bad_day_conv': 'M',
        'principal_final_flag': 0,
        'principal_initial_flag': 0,
        'holiday_calendar_name': 'DKK',
        'fixing_offset': -2
    },
    'NZD.OIS': {
        'fixed_interval': '1Y',
        'fixed_dcc': 'act/365F',
        'float_interval': '1Y',
        'float_rate_interval': '1D',
        'float_dcc': 'act/365F',
        'stub_method': 'f/s',
        'convexity_adjust': 0,
        'vol_model': 'NULL',
        'accrual_bad_day_conv': 'M',
        'pay_bad_day_conv': 'M',
        'reset_bad_day_conv': 'N',
        'principal_final_flag': 0,
       'principal_initial_flag': 0,
        'holiday_calendar_name': 'NZD',
        'fixing_offset': -2
    },
    'NZD.3ML': {
        'fixed_interval': '6M',
        'fixed_dcc': 'act/365F',
        'float_interval': '3M',
        'float_rate_interval': '3M',
        'float_dcc': 'act/365F',
        'stub_method': 'f/s',
        'convexity_adjust': 0,
        'vol_model': 'NULL',
        'accrual_bad_day_conv': 'M',
        'pay_bad_day_conv': 'M',
        'reset_bad_day_conv': 'M',
        'principal_final_flag': 0,
        'principal_initial_flag': 0,
        'holiday_calendar_name': 'NZD',
        'fixing_offset': -2
    },
    'HUF.OIS': {
        'fixed_interval': '1Y',
        'fixed_dcc': 'act/365F',
        'float_interval': '1Y',
        'float_rate_interval': '1D',
        'float_dcc': 'act/365F',
        'stub_method': 'f/s',
        'convexity_adjust': 0,
        'vol_model': 'NULL',
        'accrual_bad_day_conv': 'M',
        'pay_bad_day_conv': 'M',
        'reset_bad_day_conv': 'N',
        'principal_final_flag': 0,
        'principal_initial_flag': 0,
        'holiday_calendar_name': 'HUF',
        'fixing_offset': -2
    },
    'HUF.3ML': {
        'fixed_interval': '1Y',
        'fixed_dcc': 'act/365F',
        'float_interval': '3M',
        'float_rate_interval': '3M',
        'float_dcc': 'act/360',
        'stub_method': 'f/s',
        'convexity_adjust': 0,
        'vol_model': 'NULL',
        'accrual_bad_day_conv': 'M',
        'pay_bad_day_conv': 'M',
        'reset_bad_day_conv': 'M',
        'principal_final_flag': 0,
        'principal_initial_flag': 0,
        'holiday_calendar_name': 'HUF',
        'fixing_offset': -2
    },
    'HUF.6ML': {
        'fixed_interval': '1Y',
        'fixed_dcc': 'act/365F',
        'float_interval': '6M',
        'float_rate_interval': '6M',
        'float_dcc': 'act/360',
        'stub_method': 'f/s',
        'convexity_adjust': 0,
        'vol_model': 'NULL',
        'accrual_bad_day_conv': 'M',
        'pay_bad_day_conv': 'M',
        'reset_bad_day_conv': 'M',
        'principal_final_flag': 0,
        'principal_initial_flag': 0,
        'holiday_calendar_name': 'HUF',
        'fixing_offset': -2
    },
    'PLN.OIS': {
        'fixed_interval': '1Y',
        'fixed_dcc': 'act/365F',
        'float_interval': '1Y',
        'float_rate_interval': '1D',
        'float_dcc': 'act/365F',
        'stub_method': 'f/s',
        'convexity_adjust': 0,
        'vol_model': 'NULL',
        'accrual_bad_day_conv': 'M',
        'pay_bad_day_conv': 'M',
        'reset_bad_day_conv': 'N',
        'principal_final_flag': 0,
        'principal_initial_flag': 0,
        'holiday_calendar_name': 'PLN',
        'fixing_offset': -2
    },
    'PLN.3ML': {
        'fixed_interval': '1Y',
        'fixed_dcc': 'act/act',
        'float_interval': '3M',
        'float_rate_interval': '3M',
        'float_dcc': 'act/365F',
        'stub_method': 'f/s',
        'convexity_adjust': 0,
        'vol_model': 'NULL',
        'accrual_bad_day_conv': 'M',
        'pay_bad_day_conv': 'M',
        'reset_bad_day_conv': 'M',
        'principal_final_flag': 0,
        'principal_initial_flag': 0,
        'holiday_calendar_name': 'PLN',
        'fixing_offset': -2
    },
    'PLN.6ML': {
        'fixed_interval': '1Y',
        'fixed_dcc': 'act/act',
        'float_interval': '6M',
        'float_rate_interval': '6M',
        'float_dcc': 'act/365F',
        'stub_method': 'f/s',
        'convexity_adjust': 0,
        'vol_model': 'NULL',
        'accrual_bad_day_conv': 'M',
        'pay_bad_day_conv': 'M',
        'reset_bad_day_conv': 'M',
        'principal_final_flag': 0,
        'principal_initial_flag': 0,
        'holiday_calendar_name': 'PLN',
        'fixing_offset': -2
    },
    'CZK.OIS': {
        'fixed_interval': '1Y',
        'fixed_dcc': 'act/360',
        'float_interval': '1Y',
        'float_rate_interval': '1D',
        'float_dcc': 'act/360',
        'stub_method': 'f/s',
        'convexity_adjust': 0,
        'vol_model': 'NULL',
        'accrual_bad_day_conv': 'M',
        'pay_bad_day_conv': 'M',
        'reset_bad_day_conv': 'N',
        'principal_final_flag': 0,
        'principal_initial_flag': 0,
        'holiday_calendar_name': 'CZK',
        'fixing_offset': -2
    },
    'CZK.3ML': {
        'fixed_interval': '1Y',
        'fixed_dcc': 'act/360',
        'float_interval': '3M',
        'float_rate_interval': '3M',
        'float_dcc': 'act/360',
        'stub_method': 'f/s',
        'convexity_adjust': 0,
        'vol_model': 'NULL',
        'accrual_bad_day_conv': 'M',
        'pay_bad_day_conv': 'M',
        'reset_bad_day_conv': 'M',
        'principal_final_flag': 0,
        'principal_initial_flag': 0,
        'holiday_calendar_name': 'CZK',
        'fixing_offset': -2
    },
    'CZK.6ML': {
        'fixed_interval': '1Y',
        'fixed_dcc': 'act/360',
        'float_interval': '6M',
        'float_rate_interval': '6M',
        'float_dcc': 'act/360',
        'stub_method': 'f/s',
        'convexity_adjust': 0,
        'vol_model': 'NULL',
        'accrual_bad_day_conv': 'M',
        'pay_bad_day_conv': 'M',
        'reset_bad_day_conv': 'M',
        'principal_final_flag': 0,
        'principal_initial_flag': 0,
        'holiday_calendar_name': 'CZK',
        'fixing_offset': -2
    },
    'ILS.3ML': {
        'fixed_interval': '1Y',
        'fixed_dcc': 'act/365',
        'float_interval': '3M',
        'float_rate_interval': '3M',
        'float_dcc': 'act/365',
        'stub_method': 'f/s',
        'convexity_adjust': 0,
        'vol_model': 'NULL',
        'accrual_bad_day_conv': 'M',
        'pay_bad_day_conv': 'M',
        'reset_bad_day_conv': 'M',
        'principal_final_flag': 0,
        'principal_initial_flag': 0,
        'holiday_calendar_name': 'ILS',
        'fixing_offset': -2
    },
}

CURVE_NAMES_DICT = {
    'USD.OIS': {
        'dcrv': 'USD.OIS.ON',
        'ecrv': 'USD.OIS.ON',
    },
    'USD.1ML': {
        'dcrv': 'USD.OIS.ON',
        'ecrv': 'USD.LIBOR.1M',
    },
    'USD.3ML': {
        'dcrv': 'USD.OIS.ON',
        'ecrv': 'USD.LIBOR.3M',
    },
    'USD.6ML': {
        'dcrv': 'USD.OIS.ON',
        'ecrv': 'USD.LIBOR.6M',
    },
    'USD.3ML.IMM': {
        'dcrv': 'USD.OIS.ON',
        'ecrv': 'USD.LIBOR.3M',
    },
    'CHF.OIS': {
        'dcrv': 'CHF.TOIS.ON',
        'ecrv': 'CHF.TOIS.ON',
    },
    'CHF.1ML': {
        'dcrv': 'CHF.TOIS.ON',
        'ecrv': 'CHF.LIBOR.1M',
    },
    'CHF.3ML': {
        'dcrv': 'CHF.TOIS.ON',
        'ecrv': 'CHF.LIBOR.3M',
   },
    'CHF.6ML': {
        'dcrv': 'CHF.TOIS.ON',
        'ecrv': 'CHF.LIBOR.6M',
    },
    'EUR.OIS': {
        'dcrv': 'EUR.EONIA.ON',
        'ecrv': 'EUR.EONIA.ON',
    },
    'EUR.1ML': {
        'dcrv': 'EUR.EONIA.ON',
        'ecrv': 'EUR.EURIBOR.1M',
    },
    'EUR.3ML': {
        'dcrv': 'EUR.EONIA.ON',
        'ecrv': 'EUR.EURIBOR.3M',
    },
    'EUR.6ML': {
        'dcrv': 'EUR.EONIA.ON',
        'ecrv': 'EUR.EURIBOR.6M',
    },
    'EUR.3ML.IMM': {
        'dcrv': 'EUR.EONIA.ON',
        'ecrv': 'EUR.EURIBOR.3M',
    },
    'EUR.6ML.IMM': {
        'dcrv': 'EUR.EONIA.ON',
        'ecrv': 'EUR.EURIBOR.6M',
    },
    'GBP.OIS': {
        'dcrv': 'GBP.SONIA.ON',
        'ecrv': 'GBP.SONIA.ON',
    },
    'GBP.1ML': {
        'dcrv': 'GBP.SONIA.ON',
        'ecrv': 'GBP.LIBOR.1M',
    },
    'GBP.3ML': {
        'dcrv': 'GBP.SONIA.ON',
        'ecrv': 'GBP.LIBOR.3M',
    },
    'GBP.6ML': {
        'dcrv': 'GBP.SONIA.ON',
        'ecrv': 'GBP.LIBOR.6M',
    },
    'GBP.3ML.IMM': {
        'dcrv': 'GBP.SONIA.ON',
        'ecrv': 'GBP.LIBOR.3M',
    },
    'GBP.6ML.IMM': {
        'dcrv': 'GBP.SONIA.ON',
        'ecrv': 'GBP.LIBOR.6M',
    },
    'CAD.OIS': {
        'dcrv': 'CAD.CORRA.ON',
        'ecrv': 'CAD.CORRA.ON',
    },
    'CAD.3ML': {
        'dcrv': 'CAD.CORRA.ON',
        'ecrv': 'CAD.CDOR.3M',
    },
    'CAD.3ML.SD': {
        'dcrv': 'CAD.CDOR.3M',
        'ecrv': 'CAD.CDOR.3M',
    },
    'JPY.OIS': {
        'dcrv': 'JPY.TONAR.ON',
        'ecrv': 'JPY.TONAR.ON',
    },
    'JPY.1ML': {
        'dcrv': 'JPY.TONAR.ON',
        'ecrv': 'JPY.LIBOR.1M',
    },
    'JPY.3ML': {
        'dcrv': 'JPY.TONAR.ON',
        'ecrv': 'JPY.LIBOR.3M',
    },
    'JPY.6ML': {
        'dcrv': 'JPY.TONAR.ON',
        'ecrv': 'JPY.LIBOR.6M',
    },
    'JPY.6ML.SD': {
        'dcrv': 'JPY.LIBOR.6M',
        'ecrv': 'JPY.LIBOR.6M',
    },
    'SEK.OIS': {
        'dcrv': 'SEK.STINA.ON',
        'ecrv': 'SEK.STINA.ON',
    },
    'SEK.3ML': {
        'dcrv': 'SEK.STINA.ON',
        'ecrv': 'SEK.STIBOR.3M',
    },
    'AUD.OIS': {
        'dcrv': 'AUD.AONIA.ON',
        'ecrv': 'AUD.AONIA.ON',
    },
    'AUD.3ML': {
        'dcrv': 'AUD.AONIA.ON',
        'ecrv': 'AUD.BBSW.3M',
    },
    'AUD.6ML': {
        'dcrv': 'AUD.AONIA.ON',
        'ecrv': 'AUD.BBSW.6M',
    },
    'NOK.OIS': {
        'dcrv': 'NOK.NOWA.ON',
        'ecrv': 'NOK.NOWA.ON',
    },
    'NOK.3ML': {
        'dcrv': 'NOK.NOWA.ON',
        'ecrv': 'NOK.NIBOR.3M',
    },
    'NOK.6ML': {
        'dcrv': 'NOK.NOWA.ON',
        'ecrv': 'NOK.NIBOR.6M',
    },
    'DKK.OIS': {
        'dcrv': 'DKK.CITA.ON',
        'ecrv': 'DKK.CITA.ON',
    },
    'DKK.3ML': {
        'dcrv': 'DKK.CITA.ON',
        'ecrv': 'DKK.CIBOR.3M',
    },
    'DKK.6ML': {
        'dcrv': 'DKK.CITA.ON',
       'ecrv': 'DKK.CIBOR.6M',
    },
    'NZD.OIS': {
        'dcrv': 'NZD.NONIA.ON',
        'ecrv': 'NZD.NONIA.ON',
    },
    'NZD.3ML': {
        'dcrv': 'NZD.NONIA.ON',
        'ecrv': 'NZD.BBR.3M',
    },
    'HUF.OIS': {
        'dcrv': 'HUF.HUFONIA.ON',
        'ecrv': 'HUF.HUFONIA.ON',
    },
    'HUF.3ML': {
        'dcrv': 'HUF.HUFONIA.ON',
        'ecrv': 'HUF.BUBOR.3M',
    },
    'HUF.6ML': {
        'dcrv': 'HUF.HUFONIA.ON',
        'ecrv': 'HUF.BUBOR.6M',
    },
    'PLN.OIS': {
        'dcrv': 'PLN.POLONIA.ON',
        'ecrv': 'PLN.POLONIA.ON',
    },
    'PLN.3ML': {
        'dcrv': 'PLN.POLONIA.ON',
        'ecrv': 'PLN.WIBOR.3M',
    },
    'PLN.6ML': {
        'dcrv': 'PLN.POLONIA.ON',
        'ecrv': 'PLN.WIBOR.6M',
    },
    'CZK.OIS': {
        'dcrv': 'CZK.CZEONIA.ON',
        'ecrv': 'CZK.CZEONIA.ON',
    },
    'CZK.3ML': {
        'dcrv': 'CZK.CZEONIA.ON',
        'ecrv': 'CZK.PRIBOR.3M',
    },
    'CZK.6ML': {
        'dcrv': 'CZK.CZEONIA.ON',
        'ecrv': 'CZK.PRIBOR.6M',
    },
    'ILS.3ML': {
        'dcrv': 'ILS.TELBOR.3M',
        'ecrv': 'ILS.TELBOR.3M',
    }
}

VAL_DATE_CONV_DICT = {
    'USD.OIS': [
        ('2d,BM', 'USD')
    ],
    'USD.1ML': [
        ('1d,BF', 'GBP'),
        ('1d,BF', 'GBP+USD.FX'),
    ],
    'USD.3ML': [
        ('1d,BF', 'GBP'),
        ('1d,BF', 'GBP+USD.FX'),
    ],
    'USD.6ML': [
        ('1d,BF', 'GBP'),
        ('1d,BF', 'GBP+USD.FX'),
    ],
    'USD.3ML.IMM': [
        ('1d,BF', 'GBP'),
        ('1d,BF', 'GBP+USD.FX'),
    ],
    'CHF.OIS': [
        ('2d,BM', 'CHF'),
    ],
    'CHF.1ML': [
        ('1d,BF', 'GBP'),
        ('1d,BF', 'GBP+CHF'),
    ],
    'CHF.3ML': [
        ('1d,BF', 'GBP'),
        ('1d,BF', 'GBP+CHF'),
    ],
    'CHF.6ML': [
        ('1d,BF', 'GBP'),
       ('1d,BF', 'GBP+CHF'),
    ],
    'EUR.OIS': [
        ('2d,BF', 'EUR'),
    ],
    'EUR.1ML': [
        ('2d,BF', 'EUR'),
    ],
    'EUR.3ML': [
        ('2d,BF', 'EUR'),
    ],
    'EUR.6ML': [
        ('2d,BF', 'EUR'),
    ],
    'EUR.3ML.IMM': [
        ('2d,BF', 'EUR'),
    ],
    'EUR.6ML.IMM': [
        ('2d,BF', 'EUR'),
    ],
    'GBP.OIS': [
        ('0d,BF', 'GBP'),
    ],
    'GBP.1ML': [
        ('0d,BF', 'GBP'),
    ],
    'GBP.3ML': [
        ('0d,BF', 'GBP'),
    ],
    'GBP.6ML': [
       ('0d,BF', 'GBP'),
    ],
    'GBP.3ML.IMM': [
        ('0d,BF', 'GBP'),
    ],
    'GBP.6ML.IMM': [
        ('0d,BF', 'GBP'),
    ],
    'CAD.OIS': [
        ('0d,BF', 'CAD'),
    ],
    'CAD.3ML': [
        ('0d,BF', 'CAD'),
    ],
    'CAD.3ML.SD': [
        ('0d,BF', 'CAD'),
    ],
    'JPY.OIS': [
        ('2d,BF', 'JPY'),
    ],
    'JPY.1ML': [
        ('1d,BF', 'GBP'),
        ('1d,BF', 'GBP+JPY'),
    ],
    'JPY.3ML': [
        ('1d,BF', 'GBP'),
        ('1d,BF', 'GBP+JPY'),
    ],
    'JPY.6ML': [
        ('1d,BF', 'GBP'),
        ('1d,BF', 'GBP+JPY'),
    ],
    'JPY.6ML.SD': [
        ('1d,BF', 'GBP'),
        ('1d,BF', 'GBP+JPY'),
    ],
    'SEK.OIS': [
        ('2d,BF', 'SEK'),
    ],
    'SEK.3ML': [
        ('2d,BF', 'SEK'),
    ],
    'AUD.OIS': [
        ('1d,BF', 'AUD'),
    ],
    'AUD.3ML': [
        ('1d,BF', 'AUD'),
    ],
    'AUD.6ML': [
        ('1d,BF', 'AUD'),
    ],
    'NOK.OIS': [
        ('2d,BF', 'NOK'),
    ],
    'NOK.3ML': [
        ('2d,BF', 'NOK'),
    ],
    'NOK.6ML': [
        ('2d,BF', 'NOK'),
    ],
    'DKK.OIS': [
        ('2d,BF', 'DKK'),
    ],
    'DKK.3ML': [
        ('2d,BF', 'DKK'),
    ],
    'DKK.6ML': [
        ('2d,BF', 'DKK'),
    ],
    'NZD.OIS': [
        ('2d,BF', 'NZD'),
    ],
    'NZD.3ML': [
        ('2d,BF', 'NZD'),
    ],
    'HUF.OIS': [
        ('2d,BF', 'HUF'),
    ],
    'HUF.3ML': [
        ('2d,BF', 'HUF'),
    ],
    'HUF.6ML': [
        ('2d,BF', 'HUF'),
    ],
    'PLN.OIS': [
        ('2d,BF', 'PLN'),
    ],
    'PLN.3ML': [
        ('2d,BF', 'PLN'),
    ],
    'PLN.6ML': [
        ('2d,BF', 'PLN'),
    ],
    'CZK.OIS': [
        ('2d,BF', 'CZK'),
    ],
    'CZK.3ML': [
        ('2d,BF', 'CZK'),
    ],
    'CZK.6ML': [
        ('2d,BF', 'CZK'),
    ],
    'ILS.3ML': [
        ('2d,BF', 'ILS')
    ],
    'USD.OV1': [
        ('2d,BF', 'USD')
    ],
    'USD.OV3': [
        ('2d,BF', 'USD')
    ],
    'USD.OV6': [
        ('2d,BF', 'USD')
    ],
    'USD.1V3': [
        ('2d,BF', 'USD')
    ],
    'USD.1V6': [
        ('2d,BF', 'USD')
    ],
    'USD.3V6': [
        ('2d,BF', 'USD')
    ],
    'GBP.OV1': [
        ('0d,BF', 'GBP')
    ],
    'GBP.OV3': [
        ('0d,BF', 'GBP')
    ],
    'GBP.OV6': [
        ('0d,BF', 'GBP')
    ],
    'GBP.1V3': [
        ('0d,BF', 'GBP')
   ],
    'GBP.1V6': [
        ('0d,BF', 'GBP')
    ],
    'GBP.3V6': [
        ('0d,BF', 'GBP')
    ],
}

EXP_DATE_CONV_DICT = {
    'USD.OIS': ('M', 'USD'),
    'USD.1ML': ('M', 'GBP+USD'),
    'USD.3ML': ('M', 'GBP+USD'),
    'USD.6ML': ('M', 'GBP+USD'),
    'USD.3ML.IMM': ('M', 'GBP+USD'),
    'CHF.OIS': ('M', 'USD'),
    'CHF.1ML': ('M', 'GBP+CHF'),
    'CHF.3ML': ('M', 'GBP+CHF'),
    'CHF.6ML': ('M', 'GBP+CHF'),
    'EUR.OIS': ('M', 'EUR'),
    'EUR.1ML': ('M', 'EUR'),
    'EUR.3ML': ('M', 'EUR'),
    'EUR.6ML': ('M', 'EUR'),
    'EUR.3ML.IMM': ('M', 'EUR'),
    'EUR.6ML.IMM': ('M', 'EUR'),
    'GBP.OIS': ('M', 'GBP'),
    'GBP.1ML': ('M', 'GBP'),
    'GBP.3ML': ('M', 'GBP'),
    'GBP.6ML': ('M', 'GBP'),
    'GBP.3ML.IMM': ('M', 'GBP'),
    'GBP.6ML.IMM': ('M', 'GBP'),
    'CAD.3ML': ('M', 'CAD'),
    'CAD.3ML.SD': ('M', 'CAD'),
    'JPY.6ML': ('M', 'GBP+JPY'),
    'JPY.6ML.SD': ('M', 'GBP+JPY'),
}

YCF_CAL_DICT = {
    'USD.OIS': 'USD',
    'USD.1ML': 'USD',
    'USD.3ML': 'USD',
    'USD.6ML': 'USD',
    'USD.3ML.IMM': 'USD',
    'CHF.OIS': 'CHF',
    'CHF.1ML': 'CHF',
    'CHF.3ML': 'CHF',
    'CHF.6ML': 'CHF',
    'EUR.OIS': 'EUR',
    'EUR.1ML': 'EUR',
    'EUR.3ML': 'EUR',
    'EUR.6ML': 'EUR',
    'EUR.6ML.IMM': 'EUR',
    'GBP.OIS': 'GBP',
    'GBP.1ML': 'GBP',
    'GBP.3ML': 'GBP',
    'GBP.6ML': 'GBP',
    'GBP.6ML.IMM': 'GBP',
    'CAD.3ML': 'CAD',
    'CAD.3ML.SD': 'CAD',
    'JPY.6ML': 'JPY',
    'JPY.6ML.SD': 'JPY',
}


BASIS_CONV_DICT = {
    'USD.OV1': {
        'base_curve': 'USD.1ML',
        'base_float_interval': '1M',
        'base_float_rate_interval': '1M',
        'base_float_dcc': 'act/360',
        'spd_curve': 'USD.OIS',
        'spd_float_interval': '1M',
        'spd_float_rate_interval': '1D',
        'spd_float_dcc': 'act/360',
    },
    'USD.OV3': {
        'base_curve': 'USD.3ML',
        'base_float_interval': '3M',
        'base_float_rate_interval': '3M',
        'base_float_dcc': 'act/360',
        'spd_curve': 'USD.OIS',
        'spd_float_interval': '3M',
        'spd_float_rate_interval': '1D',
        'spd_float_dcc': 'act/360',
    },
    'USD.OV6': {
        'base_curve': 'USD.6ML',
        'base_float_interval': '6M',
        'base_float_rate_interval': '6M',
        'base_float_dcc': 'act/360',
        'spd_curve': 'USD.OIS',
        'spd_float_interval': '6M',
        'spd_float_rate_interval': '1D',
        'spd_float_dcc': 'act/360',
    },
    'USD.1V3': {
        'base_curve': 'USD.3ML',
        'base_float_interval': '3M',
        'base_float_rate_interval': '3M',
        'base_float_dcc': 'act/360',
        'spd_curve': 'USD.1ML',
        'spd_float_interval': '3M',
        'spd_float_rate_interval': '1M',
        'spd_float_dcc': 'act/360',
    },
    'USD.1V6': {
        'base_curve': 'USD.6ML',
        'base_float_interval': '6M',
        'base_float_rate_interval': '6M',
        'base_float_dcc': 'act/360',
        'spd_curve': 'USD.1ML',
        'spd_float_interval': '6M',
        'spd_float_rate_interval': '1M',
        'spd_float_dcc': 'act/360',
    },
    'USD.3V6': {
        'base_curve': 'USD.6ML',
        'base_float_interval': '6M',
        'base_float_rate_interval': '6M',
        'base_float_dcc': 'act/360',
        'spd_curve': 'USD.3ML',
        'spd_float_interval': '6M',
        'spd_float_rate_interval': '3M',
        'spd_float_dcc': 'act/360',
    },
    'GBP.OV1': {
        'base_curve': 'GBP.OIS',
        'base_float_interval': '1M',
        'base_float_rate_interval': '1D',
        'base_float_dcc': 'act/365F',
        'spd_curve': 'GBP.1ML',
        'spd_float_interval': '1M',
        'spd_float_rate_interval': '1M',
        'spd_float_dcc': 'act/365F',
    },
    'GBP.OV3': {
        'base_curve': 'GBP.OIS',
        'base_float_interval': '1M',
        'base_float_rate_interval': '1D',
        'base_float_dcc': 'act/365F',
        'spd_curve': 'GBP.3ML',
        'spd_float_interval': '3M',
        'spd_float_rate_interval': '3M',
        'spd_float_dcc': 'act/365F',
    },
    'GBP.OV6': {
        'base_curve': 'GBP.OIS',
        'base_float_interval': '1M',
        'base_float_rate_interval': '1D',
        'base_float_dcc': 'act/365F',
        'spd_curve': 'GBP.6ML',
        'spd_float_interval': '6M',
        'spd_float_rate_interval': '6M',
        'spd_float_dcc': 'act/365F',
    },
    'GBP.1V3': {
        'base_curve': 'GBP.3ML',
        'base_float_interval': '3M',
        'base_float_rate_interval': '3M',
        'base_float_dcc': 'act/365F',
        'spd_curve': 'GBP.1ML',
        'spd_float_interval': '3M',
        'spd_float_rate_interval': '1M',
        'spd_float_dcc': 'act/365F',
    },
    'GBP.1V6': {
        'base_curve': 'GBP.6ML',
        'base_float_interval': '6M',
        'base_float_rate_interval': '6M',
        'base_float_dcc': 'act/365F',
        'spd_curve': 'GBP.1ML',
        'spd_float_interval': '6M',
        'spd_float_rate_interval': '1M',
        'spd_float_dcc': 'act/365F',
    },
    'GBP.3V6': {
        'base_curve': 'GBP.6ML',
        'base_float_interval': '6M',
        'base_float_rate_interval': '6M',
        'base_float_dcc': 'act/365F',
        'spd_curve': 'GBP.3ML',
        'spd_float_interval': '6M',
        'spd_float_rate_interval': '3M',
        'spd_float_dcc': 'act/365F',
    },

}